#ifndef SERVICECOMMON_GLOBAL_H
#define SERVICECOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVICECOMMON_LIBRARY)
#  define SERVICECOMMON_EXPORT Q_DECL_EXPORT
#else
#  define SERVICECOMMON_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVICECOMMON_GLOBAL_H
